title = "python for Beginners."
file_type = input("Enter your file name: ")
print(title)
print(title.title())
print(title.capitalize())
print(title.casefold()) #kind of lowercase
print(title.count('o', 0, 9)) #find a character count in a variable of string
print(title.encode("utf-8", "strict"))
print(file_type.endswith('.py'))
print(title.find('n', 0))
print(title.index('y'))
print(title.upper())
print(title.lower())
print("FOR".casefold() in title.casefold())
name = input('Enter your name: ')
print(name)
print('your name is ' + name)
print('your name is', name)
print(f'your name is {name}')
print(f'your name is {name.capitalize()}')
print(f'your name is {name.upper()}')
print(f'your name is {name.casefold()}')
print(f'your name is {name.lower()}')
print(name.count('a', 0, 7))
print(name.encode('utf-8', 'strict'))
print(file_type.endswith('.py'))
print(name.find('i'))
print(name.index('r'))
print('rafi'.lower() in name.lower())